server:
  port: 8080

bot:
  name: BikkulGoodMorningBot
  token: 6684537511:AAEpUeDlsCM9zzzz7wwgKR7eoDoK4Zib1Lw

  api:
     kandinsky:
      endpoint:
        base_url: http://localhost:8090
        generate_path: /generate/

      client:
        buffer_size: 5242880


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://bikkul_telegram_bot_db_user:BTGcIEaUMLhZyT9plWzYj0lK51v24M8T@dpg-cm71skun7f5s73dahtd0-a/bikkul_telegram_bot_db
    username: bikkul_telegram_bot_db_user
    password: BTGcIEaUMLhZyT9plWzYj0lK51v24M8T
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            dataSource: spring.datasource
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
          scheduler:
            instanceName: message-printer
            instanceId: AUTO